name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x

      - name: Test backend
        run: cd backend && yarn --frozen-lockfile && yarn build

      - name: Test frontend
        run: cd frontend && yarn --frozen-lockfile && yarn build
